FROM ubuntu:latest

WORKDIR /home/server/js

RUN apt-get update && apt-get install curl -y &&\
  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  apt-get install nodejs -y && \
  rm -rf node_modules && \
  npm install webpack -g && \
  npm install

CMD webpack --watch --watch-polling