FROM ubuntu:latest

# INSTALL NODEJS
RUN apt-get update && apt-get install curl -y &&\
  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  apt-get install nodejs -y

#SETUP SERVER
WORKDIR /home/server
RUN rm -rf node_modules
CMD npm install --no-bin-links
#CMD node ./src/main.js