FROM ubuntu:latest

# INSTALL NODEJS & WEBPACK
RUN apt-get update && apt-get install curl -y && \
  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  apt-get install nodejs -y && \
  npm install webpack -g

#SETUP WEBPACK
WORKDIR /home/webpack/js
RUN rm -rf node_modules && \
  npm install