FROM ubuntu:latest

# INSTALL NODEJS
RUN apt-get update && apt-get install curl -y &&\
  curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
  apt-get install nodejs -y

#SETUP SERVER
ADD package.json /tmp/package.json
RUN cd /tmp && \
  npm install && \
  cp -a /tmp/node_modules /home/server